import { STORAGE_KEYS } from "@/lib/storage/keys";

/** All localStorage keys that should sync to the server for an athlete. */
export const SYNC_STORAGE_KEYS = [
  STORAGE_KEYS.CURRENT_WEEK,
  STORAGE_KEYS.CURRENT_WEEK_START,
  STORAGE_KEYS.PLANNING_WEEK,
  STORAGE_KEYS.WEEKLY_PLANNER,
  STORAGE_KEYS.SCHEDULE_SNAPSHOTS,
  STORAGE_KEYS.COMPLETED_WORKOUTS,
  STORAGE_KEYS.EXECUTION_HISTORY,
  STORAGE_KEYS.WEIGHT_HISTORY,
  STORAGE_KEYS.VAULT_RUN_PRS,
  STORAGE_KEYS.VAULT_PR_HISTORY,
  STORAGE_KEYS.SPRINT_PRS,
  STORAGE_KEYS.SPRINT_PR_HISTORY,
  STORAGE_KEYS.STRENGTH_PRS,
  STORAGE_KEYS.STRENGTH_PR_HISTORY,
  STORAGE_KEYS.VAULT_LOGS,
  STORAGE_KEYS.VAULT_STEP_REFERENCES,
  STORAGE_KEYS.POLE_INVENTORY,
  STORAGE_KEYS.POLE_BAGS,
  STORAGE_KEYS.RECENT_POLE_IDS,
  STORAGE_KEYS.MIGRATION_V1,
] as const;

export type SyncStorageKey = (typeof SYNC_STORAGE_KEYS)[number];

export const COACH_VIEWING_ATHLETE_KEY = "coachViewingAthleteId";
export const SYNC_CONTEXT_KEY = "syncContextAthleteId";
